# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-06-28 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0618_auto_20220622_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancemanagementsystemgroup',
            name='group_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
