# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-14 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildlifecompliance', '0619_auto_20220809_0953'),
        ('wildlifecompliance', '0619_auto_20220628_1325'),
    ]

    operations = [
    ]
